# Refer to the wiki for more information.
# https://wiki.hypr.land/Configuring/

disable_logs = false

###############
### SOURCES ###
###############

# # You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
source = ~/.config/hypr/src/autostart.conf
source = ~/.config/hypr/src/input.conf
source = ~/.config/hypr/src/keybindings.conf
source = ~/.config/hypr/src/monitors.conf
source = ~/.config/hypr/src/myPrograms.conf
source = ~/.config/hypr/src/theme.conf

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_THEME,volantes_cursors
env = HYPRCURSOR_THEME,volantes_cursors
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24

env = QT_QPA_PLATFORM,wayland;xcb
env = GDK_BACKEND,wayland,x11
env = CLUTTER_BACKEND,wayland


###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}
