#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
    kb_layout = us-cz-custom(basic)
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        #natural_scroll = false
        #scroll_factor = 1.0
        #tap-to-click = true
        #scroll-method = edge
        #left-handed = false
    }
}

# See https://wiki.hypr.land/Configuring/Gestures
gestures {
    #workspace-swipe = true
    #workspace-swipe-fingers = 3
    #workspace-swipe-distance = 300
}

# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
# device {
# }
