################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
monitor = eDP-1, 1920x1080@60, 0x0, 1 

monitor=,preferred,auto,auto

bindl = , switch:on:Lid Switch, exec, hyprctl keyword monitor "eDP-1, disable" # The built-in monitor turns off if it's closed
bindl = , switch:off:Lid Switch, exec, hyprctl keyword monitor "eDP-1, 1920x1080@60, 0x0, 1" # The built-in monitor turns on if it's open
